export const ROOT = {
  // mutations
  MUTATE_LANGUAGES: 'MUTATE_LANGUAGES',
  MUTATE_CURRENT_LANGUAGE: 'MUTATE_CURRENT_LANGUAGE',
  MUTATE_PREFERRED_LANGUAGE: 'MUTATE_PREFERRED_LANGUAGE',
  MUTATE_YOUTUBE_API_READY: 'MUTATE_YOUTUBE_API_READY',
  MUTATE_I18N: 'MUTATE_I18N',
  MUTATE_CLIENT_BANNERS_LOADED: 'MUTATE_CLIENT_BANNERS_LOADED',
  // actions
  FETCH_BASIC_DATA: 'FETCH_BASIC_DATA',
  FETCH_BANNERS: 'FETCH_BANNERS',
  FETCH_LANGUAGE_OFFER_I18N: 'FETCH_LANGUAGE_OFFER_I18N',
  FETCH_LANGUAGES: 'FETCH_LANGUAGES',
  MUTATE_SHUFFLE_AND_APPEND_BANNERS: 'MUTATE_SHUFFLE_AND_APPEND_BANNERS',
  SET_CURRENT_LANGUAGE: 'SET_CURRENT_LANGUAGE',
  SET_YOUTUBE_API_READY: 'SET_YOUTUBE_API_READY',
  SET_ALTERNATES: 'SET_ALTERNATES',

  INIT_CLIENT: 'INIT_CLIENT',

  // getters
  IS_RTL: 'IS_RTL',
  IS_ASIA: 'IS_ASIA',
  IS_EN: 'IS_EN',
  IS_JP: 'IS_JP',
  IS_CN: 'IS_CN',
  PREFERRED_LANGUAGE: 'PREFERRED_LANGUAGE',
  LANGUAGES_FOR_LANG_SELECTOR: 'LANGUAGES_FOR_LANG_SELECTOR',
};

export const SETTINGS = {
  // mutations
  MUTATE_SOCIALS: 'MUTATE_SOCIALS',
  MUTATE_SOCIAL_LINKS: 'MUTATE_SOCIAL_LINKS',
  MUTATE_CURRENCY_SELECTED: 'MUTATE_CURRENCY_SELECTED',
  MUTATE_LANGUAGE_OFFER_HIDDEN: 'MUTATE_LANGUAGE_OFFER_HIDDEN',
  MUTATE_PRIVACY_POLICY_HIDDEN: 'MUTATE_PRIVACY_POLICY_HIDDEN',
  // actions
  FETCH_SETTINGS: 'FETCH_SETTINGS',
  FETCH_SOCIAL_LINKS: 'FETCH_SOCIAL_LINKS',
  GET_CURRENCY_SELECTED: 'GET_CURRENCY_SELECTED',
  GET_LANGUAGE_OFFER_HIDDEN: 'GET_LANGUAGE_OFFER_HIDDEN',
  GET_PRIVACY_POLICY_HIDDEN: 'GET_PRIVACY_POLICY_HIDDEN',
  SET_CURRENCY_SELECTED: 'SET_CURRENCY_SELECTED',
  SET_LANGUAGE_OFFER_HIDDEN: 'SET_LANGUAGE_OFFER_HIDDEN',
  SET_PRIVACY_POLICY_HIDDEN: 'SET_PRIVACY_POLICY_HIDDEN',
  READ_LOCALSTORAGE_SETTINGS: 'READ_LOCALSTORAGE_SETTINGS',
  // getters
};

export const VIEWPORT = {
  // mutations
  MUTATE_IS_WINDOW_ACTIVE: 'MUTATE_IS_WINDOW_ACTIVE',
  MUTATE_OVERLAY_VISIBILITY: 'MUTATE_OVERLAY_VISIBILITY',
  MUTATE_VIEWPORT_WIDTH: 'MUTATE_VIEWPORT_WIDTH',
  MUTATE_VIEWPORT_HEIGHT: 'MUTATE_VIEWPORT_HEIGHT',
  MUTATE_SCROLL_TOP: 'MUTATE_SCROLL_TOP',
  MUTATE_BREAKPOINT: 'MUTATE_BREAKPOINT',
  MUTATE_USER_DEVICE_TYPE: 'MUTATE_USER_DEVICE_TYPE',
  MUTATE_BOTTOM_ZONE_HEIGHT: 'MUTATE_BOTTOM_ZONE_HEIGHT',
  // Actions
  LISTEN_TO_WINDOW_ACTIVE: 'LISTEN_TO_WINDOW_ACTIVE',
  LISTEN_TO_WINDOW_RESIZE: 'LISTEN_TO_WINDOW_RESIZE',
  LISTEN_TO_WINDOW_SCROLL: 'LISTEN_TO_WINDOW_SCROLL',
  ON_WINDOW_ACTIVE: 'ON_WINDOW_ACTIVE',
  ON_RESIZE_CALLBACK: 'ON_RESIZE_CALLBACK',
  ON_SCROLL_CALLBACK: 'ON_SCROLL_CALLBACK',
  SET_SCROLL_TOP: 'SET_SCROLL_TOP',
  SET_BREAKPOINT: 'SET_BREAKPOINT',
  SET_BOTTOM_ZONE_HEIGHT: 'SET_BOTTOM_ZONE_HEIGHT',
  SET_OVERLAY_VISIBILITY: 'SET_OVERLAY_VISIBILITY',
  // Getters
  IS_WINDOW_ACTIVE: 'IS_WINDOW_ACTIVE',
  IS_DESKTOP_WIDTH: 'IS_DESKTOP_WIDTH',
  IS_LARGE_WIDTH: 'IS_LARGE_WIDTH',
  IS_MOBILE_WIDTH: 'IS_MOBILE_WIDTH',
  IS_MOBILE_BREAKPOINT: 'IS_MOBILE_BREAKPOINT',
  VIEWPORT_WIDTH: 'VIEWPORT_WIDTH',
  VIEWPORT_HEIGHT: 'VIEWPORT_HEIGHT',
  SCROLL_TOP: 'SCROLL_TOP',
  BREAKPOINT: 'BREAKPOINT',
  MUTATE_LOCK_SCROLL: 'MUTATE_LOCK_SCROLL',
  SET_LOCK_SCROLL: 'SET_LOCK_SCROLL',
  IS_ONLY_MOBILE_BREAKPOINT: 'IS_ONLY_MOBILE_BREAKPOINT',
};

export const MENU = {
  // mutations
  MUTATE_MOBILE_MENU_OPENED: 'MUTATE_MOBILE_MENU_OPENED',
  MUTATE_SCROLL_BEFORE_OPENED: 'MUTATE_SCROLL_BEFORE_OPENED',
  MUTATE_SEARCH_OPENED: 'MUTATE_SEARCH_OPENED',
  MUTATE_MOBILE_MENU: 'MUTATE_MOBILE_MENU',
  MUTATE_DESKTOP_MENU: 'MUTATE_DESKTOP_MENU',
  // actions
  FETCH_MOBILE_MENU: 'FETCH_MOBILE_MENU',
  FETCH_DESKTOP_MENU: 'FETCH_DESKTOP_MENU',
  OPEN_MOBILE_MENU: 'OPEN_MOBILE_MENU',
  CLOSE_MOBILE_MENU: 'CLOSE_MOBILE_MENU',
  SET_SCROLL_BEFORE_OPENED: 'SET_SCROLL_BEFORE_OPENED',
  OPEN_SEARCH: 'OPEN_SEARCH',
  CLOSE_SEARCH: 'CLOSE_SEARCH',
};

export const FOOTER = {
  // mutations
  MUTATE_MENU: 'MUTATE_MENU',
  MUTATE_IS_SHOWN: 'MUTATE_IS_SHOWN',
  // actions
  FETCH_MENU: 'FETCH_MENU',
  HIDE: 'HIDE',
  SHOW: 'SHOW',
};

export const TICKERS = {
  // mutations
  MUTATE_CURRENCY: 'MUTATE_CURRENCY',
  MUTATE_META: 'MUTATE_META',
  MUTATE_COINS: 'MUTATE_COINS',
  MUTATE_CURRENCIES: 'MUTATE_CURRENCIES',
  MUTATE_GRAPHS: 'MUTATE_GRAPHS',
  MUTATE_PROMISE_DATA: 'MUTATE_PROMISE_DATA',
  MUTATE_LIVE_DATA_MOBILE_POPUP_VISIBILITY: 'MUTATE_LIVE_DATA_MOBILE_POPUP_VISIBILITY',
  MUTATE_TICKER_DATA_FROM_POST: 'MUTATE_TICKER_DATA_FROM_POST',
  MUTATE_RAW_RATES: 'MUTATE_RAW_RATES',
  // actions
  SET_CURRENCY: 'SET_CURRENCY',
  VALIDATE_PAIRS: 'VALIDATE_PAIRS',
  SET_PROMISE_DATA: 'SET_PROMISE_DATA',
  FETCH_TICKERS_DATA: 'FETCH_TICKERS_DATA',
  FETCH_TICKERS_META: 'FETCH_TICKERS_META',
  FETCH_TICKERS_GRAPHS: 'FETCH_TICKERS_GRAPHS',
  FETCH_TICKERS: 'FETCH_TICKERS',
  SUBSCRIBE_TICKERS: 'SUBSCRIBE_TICKERS',
  START_TICKERS_DATA_SHORT_POLLING: 'START_TICKERS_DATA_SHORT_POLLING',
  CHANGE_LIVE_DATA_MOBILE_POPUP_VISIBILITY: 'CHANGE_LIVE_DATA_MOBILE_POPUP_VISIBILITY',
  SET_TICKER_DATA_FROM_POST: 'SET_TICKER_DATA_FROM_POST',
  // getters
  SIGN: 'SIGN',
  GET_CURRENCY_SELECTED: 'GET_CURRENCY_SELECTED',
  DESKTOP_COINS_BY_CURRENCY: 'DESKTOP_COINS_BY_CURRENCY',
  MOBILE_COINS_BY_CURRENCY: 'MOBILE_COINS_BY_CURRENCY',
  META_COINS: 'META_COINS',
  POST_COINS: 'POST_COINS',
  POPULAR_CRYPTO_TO_FIAT: 'POPULAR_CRYPTO_TO_FIAT',
};

export const USER = {
  MUTATE_IP_ADDRESS: 'MUTATE_IP_ADDRESS',
};

export const POST = {
  MUTATE_POST_ID: 'MUTATE_POST_ID',
  MUTATE_PLAYER_ID: 'MUTATE_PLAYER_ID',
  SET_POST_ID: 'SET_POST_ID',
  SET_PLAYER_ID: 'SET_PLAYER_ID',
};

export const IMAGE_MODAL = {
  MUTATE_IS_SHOWN: 'MUTATE_IS_SHOWN',
  MUTATE_DATA: 'MUTATE_DATA',
  SET_IS_SHOWN: 'SET_IS_SHOWN',
  SET_DATA: 'SET_DATA',
};

export const SUBSCRIPTIONS_MODAL = {
  MUTATE_I18N: 'MUTATE_I18N',
  MUTATE_LIST_ITEMS: 'MUTATE_LIST_ITEMS',
  MUTATE_IS_SHOWN: 'MUTATE_IS_SHOWN',
  SET_IS_SHOWN: 'SET_IS_SHOWN',
  FETCH_I18N: 'FETCH_I18N',
};

export const PODCAST = {
  MUTATE_IMAGE_URL: 'MUTATE_IMAGE_URL',
  SET_IMAGE_URL: 'SET_IMAGE_URL',
};
