---

- hosts: all
  gather_facts: false
  strategy: free
  tasks:

  - name: Include variables
    include_vars: vars/.env

  - name: Log into docker private registry and force re-authorization
    docker_login:
      registry: registry.ctgroup.io
      username: "gitlab-ci-token"
      password: "{{ lookup('env', 'CI_BUILD_TOKEN') }}"
      reauthorize: true

  - name: "Pull new images on target hosts"
    docker_image:
      name: "{{ image }}"
      source: "pull"
      force_source: yes
